name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Allow the action to push back to the repo using the GITHUB_TOKEN
          persist-credentials: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Prepare site folder
        run: |
          mkdir -p site
          cp src/index.html site/index.html
          if [ -f dist/output.css ]; then cp dist/output.css site/output.css; else echo "dist/output.css missing"; fi
          sed -i 's|../dist/output.css|./output.css|g' site/index.html || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
